@Library('go-shared-lib') _

goPipeline(
    // 1. Informasi Project
    appName: 'todolist-app',
    projectDir: 'To-do-list',  // <-- Penting: karena source code Anda ada di subfolder
    
    // 2. Konfigurasi Deploy
    deployPort: '8082',        // Mapping port host (8082 -> 8080 container)
    
    // 3. Environment Variable Khusus Aplikasi ini (Database, dll)
    appEnvVars: [
        'DB_HOST': 'mysql_todo',
        'DB_PORT': '3306',
        'DB_USER': 'user_todo',
        'DB_PASSWORD': 'pass_todo',
        'DB_NAME': 'todolist_db'
    ]
    
    // Opsional (jika default library sudah benar, tidak perlu ditulis):
    // dockerUser: 'hakm2002', 
    // dockerCredId: 'docker-hub',
    // sonarCredId: 'go-token'
)
