pipeline {
    agent any

    environment {
        // Pastikan nama ini sesuai
        DOCKER_IMAGE = "hakm2002/todolist-app" 
        DOCKER_CRED_ID = "docker-hub" 
    }

    stage('SonarQube Analysis') {
    environment {
        // Pastikan nama 'sonar' ini SAMA PERSIS dengan di Global Tool Configuration
        scannerHome = tool 'sonar' 
    }
    steps {
        dir('To-do-list') { // Sesuaikan folder source code
            script {
                // 1. Generate Coverage dulu (Wajib ada biar report ga kosong)
                try {
                    sh 'go mod tidy'
                    sh 'go test ./... -coverprofile=coverage.out'
                } catch (Exception e) {
                    echo 'Warning: Unit test failed or returned error code, continuing scan...'
                }

                // 2. Ambil token 'go-token' dan simpan ke variabel SONAR_TOKEN
                withCredentials([string(credentialsId: 'go-token', variable: 'SONAR_TOKEN')]) {
                    
                    // 3. Ambil URL server dari konfigurasi Jenkins (Screenshot 2 kamu)
                    withSonarQubeEnv('SonarQube') {
                        
                        // 4. Jalankan Scanner dengan MEMAKSA token masuk lewat parameter -Dsonar.token
                        sh "${scannerHome}/bin/sonar-scanner -Dsonar.token=${SONAR_TOKEN}"
                    }
                }
            }
        }
    }
}
            steps {
                // Masuk folder dulu jika mau test
                dir('To-do-list') {
                    echo 'Building Application...'
                    // sh 'go test ./...' // (Nanti bisa diaktifkan)
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                // MASUK FOLDER To-do-list SEBELUM BUILD
                dir('To-do-list') {
                    // Tanda titik (.) berarti build direktori saat ini
                    sh "docker build -t ${DOCKER_IMAGE}:latest ."
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: DOCKER_CRED_ID, usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh "docker push ${DOCKER_IMAGE}:latest"
                }
            }
        }

        stage('Deploy to Server') {
            steps {
                script {
                    // Bagian deploy tidak perlu masuk folder karena perintah docker bersifat global
                    sh "docker network create devops-network || true"
                    
                    sh "docker stop todolist-app || true"
                    sh "docker rm todolist-app || true"

                    sh """
                    docker run -d \
                    --name todolist-app \
                    --network devops-network \
                    -p 8082:8080 \
                    -e DB_HOST=mysql_todo \
                    -e DB_PORT=3306 \
                    -e DB_USER=user_todo \
                    -e DB_PASSWORD=pass_todo \
                    -e DB_NAME=todolist_db \
                    ${DOCKER_IMAGE}:latest
                    """
                }
            }
        }
    }
    
    post {
        always { sh "docker logout || true" }
    }
}
