pipeline {
    agent any

    environment {
        // Pastikan nama ini sesuai
        DOCKER_IMAGE = "hakm2002/todolist-app" 
        DOCKER_CRED_ID = "docker-hub" 
    }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }

        // --- TAMBAHAN BARU: SONARQUBE ---
        stage('SonarQube Analysis') {
            steps {
                dir('To-do-list') {
                    script {
                        // GANTI 'SonarScanner' DENGAN NAMA DI GLOBAL TOOL CONFIGURATION ANDA
                        def scannerHome = tool 'sonar' 
                        
                        // GANTI 'sonar-server' DENGAN NAMA SERVER DI SYSTEM CONFIGURATION ANDA
                        withSonarQubeEnv('SonarQube') { 
                            sh "${scannerHome}/bin/sonar-scanner"
                        }
                    }
                }
            }
        }
        // --------------------------------

        stage('Test & Build App') {
            steps {
                // Masuk folder dulu jika mau test
                dir('To-do-list') {
                    echo 'Building Application...'
                    // sh 'go test ./...' // (Nanti bisa diaktifkan)
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                // MASUK FOLDER To-do-list SEBELUM BUILD
                dir('To-do-list') {
                    // Tanda titik (.) berarti build direktori saat ini
                    sh "docker build -t ${DOCKER_IMAGE}:latest ."
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: DOCKER_CRED_ID, usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh "docker push ${DOCKER_IMAGE}:latest"
                }
            }
        }

        stage('Deploy to Server') {
            steps {
                script {
                    // Bagian deploy tidak perlu masuk folder karena perintah docker bersifat global
                    sh "docker network create devops-network || true"
                    
                    sh "docker stop todolist-app || true"
                    sh "docker rm todolist-app || true"

                    sh """
                    docker run -d \
                    --name todolist-app \
                    --network devops-network \
                    -p 8082:8080 \
                    -e DB_HOST=mysql_todo \
                    -e DB_PORT=3306 \
                    -e DB_USER=user_todo \
                    -e DB_PASSWORD=pass_todo \
                    -e DB_NAME=todolist_db \
                    ${DOCKER_IMAGE}:latest
                    """
                }
            }
        }
    }
    
    post {
        always { sh "docker logout || true" }
    }
}
